### ISSUE TITLE
doesnt exist, read the docs for more info.

### ISSUE THREAD

**Issue by vyscond** [BananaDesk/django-phantom-pdf#10]
followed the tutorial get this when requesting the base. 
```"%s doesnt exist, read the docs for more info." % self.PHANTOMJS_BIN```
Also i'm wondering where i set the template to being rendered .-.

**Comment by toabi** [comment]
Sounds like your PhantomJS binary is not where it should be.

It will request the same URL again. Your view should therefore have one HTML-emitting code path.

**Comment by sypl** [comment]
I got htis error as well. Where should it be? /usr/bin/phantomjs? I have mine under a nvm directory. How can I make it play nice?

**Comment by toabi** [comment]
@sypl see https://github.com/BananaDesk/django-phantom-pdf#advanced-use how to adjust the django settings with proper paths

**Comment by jcarizza** [comment]
@sypl Maybe the user wich is running Django have not access to PhantomJS bin
