### ISSUE TITLE
sessionid fails

### ISSUE THREAD

**Issue by softshape** [BananaDesk/django-phantom-pdf#9]
Hi,

request.COOKIES.get('sessionid', 'nosessionid') 

fails if SESSION_COOKIE_NAME is set to any other value than 'sessionid'. In our project, for example, 

SESSION_COOKIE_NAME = "_sid"

so user session won't pass to PDF version and it fails.

**Comment by x-ip** [comment]
whops! Thanks for reporting this, seems this must be a configurable setting.
Thanks!

2015-03-10 7:07 GMT-03:00 softshape <notifications@github.com>:

> Hi,
>
> request.COOKIES.get('sessionid', 'nosessionid')
>
>    - fails if SESSION_COOKIE_NAME is set to any other value than
>    'sessionid'. In our project, for example,
>
> SESSION_COOKIE_NAME = "_sid"
>
> so user session won't pass to PDF version and it fails.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BananaDesk/django-phantom-pdf/issues/9>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by softshape** [comment]
Just change 'sessionid' to settings.SESSION_COOKIE_NAME, i.e. -

request.COOKIES.get(settings.SESSION_COOKIE_NAME, 'nosessionid')

**Comment by tzenderman** [comment]
Hey @softshape - can you send a PR?

**Comment by softshape** [comment]
No idea how to do this. Just waiting @x-ip to fix it :)

BTW @x-ip please write us when an update is available via pip. I don't want to edit dist-packages manually, really.

**Comment by toabi** [comment]
@tzenderman btw, I made a PR.

**Comment by tzenderman** [comment]
Thanks, I'll check this out today.

**Comment by tzenderman** [comment]
@softshape: This should be fixed with @toabi 's PR which was just merged into the `master` branch. Still need to do a Pypi release though...
